//===------------------------------------------------------------*- C++ -*-===//
//
// Automatically Generated by Allo (XLS [CC] Backend)
//
//===----------------------------------------------------------------------===//
// Standard C/C++ headers
#include <cstdint>

// XLS [CC] headers
#include "/xls_builtin.h"  // NOLINT
#include "xls_int.h"       // NOLINT

// Templated Types for XLS [CC]
template<typename T>
using InputChannel = __xls_channel<T, __xls_channel_dir_In>;
template<typename T>
using OutputChannel = __xls_channel<T, __xls_channel_dir_Out>;
template<typename T, int Size>
using Memory = __xls_memory<T, Size>;
template <int Width, bool Signed = true>
using ac_int = XlsInt<Width, Signed>;

void vvadd() {  // L2
  int size = 16;
  int v0[16];
  int v1[16];
  #pragma hls_unroll yes
  for (int i = 0; i < 16; ++i) {
    v0[i] = v0_read.read();
  }
  #pragma hls_unroll yes
  for (int i = 0; i < 16; ++i) {
    v1[i] = v1_read.read();
  }
  int c[16] /* int c[16] */;    // L4
  #pragma hls_unroll yes
  for (int int v3 = 0; v3 < 16; v3++) { // L5
    c[v3] = 0;  // L5
  }
  #pragma hls_pipeline_init_interval 1
  for (int int i = 0; i < 16; i++) {    // L6
    int v5 = v0[i];     // L7
    int v6 = v1[i];     // L8
    ac_int<33, true> v7 = v5;   // L9
    ac_int<33, true> v8 = v6;   // L10
    ac_int<33, true> v9 = v7 + v8;      // L11
    int v10 = v9;       // L12
    c[i] = v10; // L13
  }
  #pragma hls_unroll yes
  for (int i = 0; i < 16; ++i) {
    out.write(c[i]);
  }
}


// ---- End core code ----
class TestBlock {
public:
    
    InputChannel<int> v0_read;
    InputChannel<int> v1_read;
    OutputChannel<int> out;
    
        
    #pragma hls_top
    void vvadd() {
        int size = 16;
        // Body is provided by EmitXlsHLS (void vvadd()).
        vvadd();
    }
    
};
