# proto-file: xls/codegen/ram_rewrite.proto
# proto-message: RamRewritesProto

rewrites {
  from_config {
    kind: RAM_ABSTRACT
    depth: 16
  }
  to_config {
    kind: RAM_1R1W
    depth: 16
  }
  from_channels_logical_to_physical: {
    key: "abstract_read_req"
    value: "v0_read_request"
  }
  from_channels_logical_to_physical: {
    key: "abstract_read_resp"
    value: "v0_read_response"
  }
  from_channels_logical_to_physical: {
    key: "abstract_write_req"
    value: "v0_write_request"
  }
  from_channels_logical_to_physical: {
    key: "write_completion"
    value: "v0_write_response"
  }
  to_name_prefix: "v0_"
}

rewrites {
  from_config {
    kind: RAM_ABSTRACT
    depth: 16
  }
  to_config {
    kind: RAM_1R1W
    depth: 16
  }
  from_channels_logical_to_physical: {
    key: "abstract_read_req"
    value: "v1_read_request"
  }
  from_channels_logical_to_physical: {
    key: "abstract_read_resp"
    value: "v1_read_response"
  }
  from_channels_logical_to_physical: {
    key: "abstract_write_req"
    value: "v1_write_request"
  }
  from_channels_logical_to_physical: {
    key: "write_completion"
    value: "v1_write_response"
  }
  to_name_prefix: "v1_"
}

rewrites {
  from_config {
    kind: RAM_ABSTRACT
    depth: 16
  }
  to_config {
    kind: RAM_1R1W
    depth: 16
  }
  from_channels_logical_to_physical: {
    key: "abstract_read_req"
    value: "c_read_request"
  }
  from_channels_logical_to_physical: {
    key: "abstract_read_resp"
    value: "c_read_response"
  }
  from_channels_logical_to_physical: {
    key: "abstract_write_req"
    value: "c_write_request"
  }
  from_channels_logical_to_physical: {
    key: "write_completion"
    value: "c_write_response"
  }
  to_name_prefix: "c_"
}
